apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: adm
spec:
  releaseName: sealed-secrets
  chart:
    repository: gcr.io/kinetic-decoder-320516/echo-v2
    name: sealed-secrets
    version: 1.6.1
