---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~5.0
spec:
  releaseName: podinfo-prod
  chart:
    git: git@github.com:korenshoshan/helm-operator-get-started.git
    path: charts/echo-v4
    ref: master
  values:
    image:
      repository: gcr.io/kinetic-decoder-320516/echo-v2
      tag: 5.0.0
    replicaCount: 3
