---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: podinfo-rc
  chart:
    git: git@github.com:korenshoshan/helm-operator-get-started.git
    path: charts/echo-v4
    ref: master
  values:
    image:
      repository: gcr.io/kinetic-decoder-320516/echo-v2
      tag: stg-5
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
