apiVersion: cert-manager.io/v1 #here I just define which server-authority- will give me the certificate  (acme)
kind: ClusterIssuer #to who i want to refer, with who I will talk. https://cert-manager.io/docs/concepts/certificate/
metadata:
  name: {{ .Values.clusterIssuer.name }} #the CA- letsencrypt
  #namespace: cert-manager
spec:
  acme: #certified issuer that gives me certificate- the 
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: {{ .Values.clusterIssuer.email }}
    server: {{ .Values.clusterIssuer.server }}
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: {{ .Values.clusterIssuer.privateKeySecretRef.name }}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: {{ .Values.clusterIssuer.class }}