apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: {{ .Values.secret.type }}
data:
  #replace this conf file in deployment(the app)
  MONGODBURL: {{- printf "\"mongodb://%s:%s@%s-mongodb-headless.%s.svc.%s/%s\"" .Values.mongodb.auth.username .Values.mongodb.auth.password .Release.Name .Release.Namespace .Values.clusterdomain .Values.mongodb.auth.database | b64enc | quote | indent 2 }} 
